### ISSUE TITLE
Cant enter 2 stage

### ISSUE THREAD

**Issue by Opos3107** [d07RiV/diabloweb#34] opened 2019-08-03 13:11 UTC
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.11 (Shareware)

**Error message:**
    
    String

**Comment by d07RiV** [comment] 2019-08-03 13:43
Duplicate of #31 - should be fixed now.

**Closed by d07RiV** 2019-08-03 13:43 UTC
