### ISSUE TITLE
Diablo not working

### ISSUE THREAD

**Issue by zzVoldemart** [d07RiV/diabloweb#86] opened 2019-09-01 09:23 UTC
I downloaded the MPQ file and got it onto my phone. iPhone X and iPhone 6S+ just to see if it would work but both get to the menu and then after I select my hero, screen goes black and no gameplay. Just touch buttons are seen on screen. Tried both on safari and google chrome. What can I do ?!

**Comment by AJenbo** [comment] 2019-09-01 09:29
Duplicate of https://github.com/d07RiV/diabloweb/issues/79

**Comment by zzVoldemart** [comment] 2019-09-01 09:42
Not a duplicate of #79 because I used different browsers

**Comment by AJenbo** [comment] 2019-09-01 10:44
On iPhone Chrome just wraps the Safari engine so it's actually the same. It's some requirement from Apple that you are only allowed to use the safari browser engine for apps on there devices.

**Comment by d07RiV** [comment] 2019-09-02 08:04
Doesn't seem to be the same issue because the original one triggers a page reload (crash) while this one lets you play but with no graphics. I had the same happen to a friend and I could see his character moving in multiplayer, and it was really weird where he had to click to go in various directions.

No idea what I could do about it though, since apple is making it impossible to debug issues on their devices.

**Comment by AJenbo** [comment] 2019-09-02 08:16
I guess that for #79 the difference is that it reloads the page after a few sec. I just assumed that was also the case here.

**Comment by schwarzjr** [comment] 2019-09-03 13:51
#79 sometimes crashes and sometimes stays on with black screen. So I would say it really is the same issue and is connected to iOS webkit and its work with wasm.

**Closed** 2020-02-05 01:23 UTC
