### ISSUE TITLE
Stuck on level 3 in first dungeon

### ISSUE THREAD

**Issue by everystone** [d07RiV/diabloweb#1] opened 2019-08-01 13:21 UTC
After entering the first dungeon, I got stuck unable to move after going down to level 2 (3?).
![image](https://i.imgur.com/nzw39Do.png)

**Comment by francoispeyret** [comment] 2019-08-01 15:08
did you play with the shareware version ?

**Comment by matthewford** [comment] 2019-08-01 19:45
same shareware

**Comment by d07RiV** [comment] 2019-08-01 20:21
That's a weird bug that I can't reproduce. Normally the shareware version should end after floor 3, but some people report floor 2 bugging out.

I added a function to export save files, please open the console and type `DownloadFile("spawn0.sv")` (or spawn1/2 etc depending on which save file you're playing) - **before** you enter the glitched level. I'll try to reproduce the problem with the save file.

**Comment by OrangBuangan** [comment] 2019-08-02 21:01
On original shareware, the player says "No way" and walks away from the steps to lvl 3.

**Comment by d07RiV** [comment] 2019-08-02 22:48
Yes, I finally managed to run the shareware so I could replicate the functionality.

**Comment by d07RiV** [comment] 2019-08-03 13:47
Okay I think the problem was related to quests trying to load, which was later replaced by a proper error message instead of generating a broken map. Should be fixed now.

**Closed by d07RiV** 2019-08-03 13:47 UTC
