### ISSUE TITLE
erro ao entrar no portal ou voltar para entrada do vilarejo

### ISSUE THREAD

**Issue by donovanrodrigues** [d07RiV/diabloweb#36] opened 2019-08-03 15:25 UTC
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.13 (Retail)

**Error message:**
    
    Unable to open save file

**Comment by d07RiV** [comment] 2019-08-03 18:27
Must be a broken save file again, I'm investigating.

Duplicate of #37

**Closed by d07RiV** 2019-08-03 18:27 UTC
