### ISSUE TITLE
Crash on using town portal

### ISSUE THREAD

**Issue by romapsih** [d07RiV/diabloweb#40] opened 2019-08-03 23:30 UTC
**Description:**
Found a town portal at 2nd level and used it.

**App version:**
DiabloWeb 1.0.14 (Shareware)

**Error message:**
    
    Unable to open save file

**User agent:**

    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15

**Save file:**

[spawn0.sv.zip](https://github.com/d07RiV/diabloweb/files/3464422/spawn0.sv.zip)

**Comment by d07RiV** [comment] 2019-08-03 23:38
Yup the save file is also broken.

Duplicate of #14, I'm looking into this.

**Closed by d07RiV** 2019-08-03 23:38 UTC
