### ISSUE TITLE
crashes every time i try and exit the dungeon back to town

### ISSUE THREAD

**Issue by mtopolinski** [d07RiV/diabloweb#100] opened 2019-09-20 15:54 UTC
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.28 (Retail)

**Error message:**
    
    Unable to open save file

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

[single_0.zip](https://github.com/d07RiV/diabloweb/files/3636762/single_0.zip)

**Comment by AJenbo** [comment] 2020-02-05 01:44
Duplicate of https://github.com/d07RiV/diabloweb/issues/98

**Closed by AJenbo** 2020-02-05 01:44 UTC
