### ISSUE TITLE
going back to town -> white screen

### ISSUE THREAD

**Issue by thk12** [d07RiV/diabloweb#14] opened 2019-08-02 14:10 UTC
when i go to town a white screen appears. sound still plays.
browser is latest chrome v 76.0.3809.87 (64 bit)

on F12 theres a JS error. i'll attach a log
[d07riv.github.io-1564754812722.log](https://github.com/d07RiV/diabloweb/files/3461582/d07riv.github.io-1564754812722.log)

**Comment by techi602** [comment] 2019-08-02 16:28
yep same error here

**Comment by nikopp** [comment] 2019-08-02 19:19
I get the white screen when I go down to level 2.

Browser is latest chrome.

**Comment by outpost34** [comment] 2019-08-02 20:28
Same here. Chrome, turns white trying to return to town from dungeon. Sound stays on.

**Comment by gwmccull** [comment] 2019-08-02 21:38
Same error when trying to go to level 2 of the dungeon. Chrome 75 on a mac

**Comment by d07RiV** [comment] 2019-08-02 22:38
Please include a save file, it's really hard to read an error log from production build.

You can get the savefiles by typing `DownloadFiles()` in devtools console (F12).

**Comment by d07RiV** [comment] 2019-08-02 22:45
Seems the game was trying to report an error but something went wrong. I'm fixing the error reporting, but the root cause is still unknown.

**Comment by Foricoso** [comment] 2019-08-03 13:11
I've downloaded the save file when the prompt asked (just after entering a town portal and getting the error), I'll try to send it to you.

**Comment by Steviadition** [comment] 2019-08-03 18:45
Got same error, going down to level 1. white screen, just sound. Chrome, Windows 10. 

Is there a solution yet?

**Comment by Foricoso** [comment] 2019-08-03 19:16
I'd just like to add that, after starting a new character today, I haven't been able to reproduce the same problem, everything works fine.

**Comment by gwmccull** [comment] 2019-08-03 22:03
Right after I posted my error above, I created a new character using MacOS Safari and I did not get the error. Played through both levels of the dungeon w/ no problem. The only difference (other than browser) is that I didn't save at all before I went to the 2nd level

**Comment by tomekk01** [comment] 2019-08-03 22:37
> Right after I posted my error above, I created a new character using MacOS Safari and I did not get the error. Played through both levels of the dungeon w/ no problem. The only difference (other than browser) is that I didn't save at all before I went to the 2nd level

I got the error on Chrome and for me the very first save was on 2nd level before taking Butcher. Before making the save I was able to go back and forth to the town several times. It seems that something was\is wrong with information about the town (?) as I was able to move between levels 2>3 (after killing the butcher) >2>1 but when tried to go to the town (via stairs in the cathedral) the game crashed. I did not had any town scrolls yet so I'm not sure if that would also crash the game.

**Comment by refractionpcsx2** [comment] 2019-08-03 22:38
Although i haven't tried it since this morning, I didn't manually save (it may have saved automatically, I didn't check) but going down to the second level of the dungeon caused a white screen for me. I tend to clear out whole levels before going down to the next one, so an auto save is highly possible

**Comment by tomekk01** [comment] 2019-08-03 22:39
> Although i haven't tried it since this morning, I didn't manually save (it may have saved automatically, I didn't check) but going down to the second level of the dungeon caused a white screen for me. I tend to clear out whole levels before going down to the next one, so an auto save is highly possible

Is there such thing as autosave in D1 after you change levels? Not sure, just asking?

**Comment by refractionpcsx2** [comment] 2019-08-03 22:40
> > Although i haven't tried it since this morning, I didn't manually save (it may have saved automatically, I didn't check) but going down to the second level of the dungeon caused a white screen for me. I tend to clear out whole levels before going down to the next one, so an auto save is highly possible
> 
> Is there such thing as autosave in D1 after you change levels? Not sure, just asking?

I don't know personally, the last time I played D1 before this, I was about 15, I'm now 37 xD

**Comment by sskras** [comment] 2019-08-03 22:44
> Is there such thing as autosave in D1 after you change levels? Not sure, just asking?

@tomekk01, there was no such thing IIRC. Every save needed to be player initiated, manual.

**Comment by refractionpcsx2** [comment] 2019-08-03 22:44
> > Is there such thing as autosave in D1 after you change levels? Not sure, just asking?
> 
> @tomekk01, there was no such thing IIRC. Every save needed to be player initiated, manual.

In that case, the white screen happens regardless of saving

**Comment by tomekk01** [comment] 2019-08-03 22:45
> > > Although i haven't tried it since this morning, I didn't manually save (it may have saved automatically, I didn't check) but going down to the second level of the dungeon caused a white screen for me. I tend to clear out whole levels before going down to the next one, so an auto save is highly possible
> > 
> > 
> > Is there such thing as autosave in D1 after you change levels? Not sure, just asking?
> 
> I don't know personally, the last time I played D1 before this, I was about 15, I'm now 37 xD

yes, same thing for me - that was actually first game I bought more than 20 years ago as teenager :D - and now it's playable in the browser :)

**Comment by d07RiV** [comment] 2019-08-03 23:26
There's two different errors. One was in shareware version when going down to level 2 - the game sometimes crashed because it was trying to load the Butcher, which does not exist in shareware files (there aren't supposed to be any quests). I fixed that error yesterday, so that part should be working normally.

The other error is that I'm seeing a lot of save files with corrupted town data. When you play the game, it saves every level you visit in your save file as a "temporary" level (so when you go back, everything is the same). When you actually save the game, it replaces all "permanent" levels with temporary ones. I'm not sure at which point the town level breaks, as I've never been able to reproduce the problem.

**Comment by d07RiV** [comment] 2019-08-03 23:39
Somehow another file is overlapping the town data, this seems like a lead.

**Comment by d07RiV** [comment] 2019-08-04 00:30
I made a small fix that removes some inconsistencies in save file handling, but I doubt it is related to the issue.

**Comment by outpost34** [comment] 2019-08-04 08:32
Thanks for the fixes! Last I played the white screen error disappeared. I made a new character though lol.

**Comment by d07RiV** [comment] 2019-08-04 14:25
Well yes, the error is with particular save files and I really have no idea how that could happen, I've read through the saving code 50 times over and can't spot any problems (and most of it is still identical to the original code).

If anyone manages to reproduce it in a reliable manner, that would be great.

**Comment by OrangBuangan** [comment] 2019-08-04 15:12
@d07RiV could this be because the save game container memory pointers?

**Comment by sskras** [comment] 2019-08-04 15:52
As I know nothing about WASM and haven't followed diabloweb history, I would like to add: if pointer concept is used here, what is his width – 32 or 64 bit?

Eg. devilution is 32-bit only app while devilutionX may be compiled as 64-bit. And the latter had _a lot_ of bugs in 64-bit mode (since the original code wasn't machine portable) at one phase, esp. in regard with save files.

**Comment by athalas88** [comment] 2019-08-04 21:40
I have this issue too. First I tried a shareware version, made a character. After that i played the full version and on that I made the same character.  Anytime I try to go back to town, it crashes, even with town portal or on foot from the level 1. Now I will try a new character, hope it will help.

**Comment by d07RiV** [comment] 2019-08-05 00:00
This is 32 bit, WASM does not support 64 bit currently (max memory is hard capped at 2GB so there's no point).

@athalas88 can you remember what you did on the new character before it started crashing? I'm fairly sure spawn and full versions shouldn't interfere with each other as they use different files.

**Comment by d07RiV** [comment] 2019-08-05 13:44
Okay I did some further digging, and it seems the fix I made 2 days ago should have solved this problem.

Reproducing on the old version is really easy - create a new character, enter church without saving, then save. Now you can't leave the church.

I'm going to close this on assumption that the problem is gone.

**Closed by d07RiV** 2019-08-05 13:44 UTC

**Comment by thk12** [comment] 2019-08-05 13:59
ty! and keep up the good work

**Comment by athalas88** [comment] 2019-08-06 12:53
Hi. I just wanted to thank you! Now works perfectly! :)

Athalas

thk12 <notifications@github.com> ezt írta (időpont: 2019. aug. 5., H 15:59):
